import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen content-between m-0 pb-[92px]`}>
        <Navbar />
        <main className="flex-grow overflow-auto h-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
